GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuaWwiLCJwYXNzd29yZCI6IiQyYiQxMCQxMjkxVUcucWlxcDhQdXVTaWNDVlcuRDhYZ3VMR2Vnc3pjbmZHd08uNHhOdUEwb1ZEdUMyZSIsImlhdCI6MTYwNDA5MjE3MH0.i-_K5eZGFQ3EVcfPpCYUsE3TNJUahNPvY6L6By1u_wE

###

GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "username":"anil",
    "password":"pass"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username":"anil",
    "password":"pass"
}